version: '3'
services:
  wyoming-piper:
    extends:
      file: docker-compose.base.yml
      service: wyoming-piper
    build:
      dockerfile: GPU.Dockerfile
    volumes:
      - ./piper/__main__.py:/usr/local/lib/python3.10/dist-packages/wyoming_piper/__main__.py
      - ./piper/process.py:/usr/local/lib/python3.10/dist-packages/wyoming_piper/process.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  wyoming-whisper:
    extends:
      file: docker-compose.base.yml
      service: wyoming-whisper
    build:
      dockerfile: GPU.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: [ "--model", "tiny-int8", "--language", "en", "--device", "cuda" ]

  wyoming-openwakeword:
    extends:
      file: docker-compose.base.yml
      service: wyoming-openwakeword
    build:
      dockerfile: GPU.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

