version: '3'
### YAML Anchors ###
x-restart: &restart
  restart: unless-stopped

####
services:
  wyoming-piper:
    build:
      context: ./piper/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10200:10200"
    command: [ "--voice", "en_US-lessac-medium" ]
    <<: [ *restart ]

  wyoming-whisper:
    build:
      context: ./whisper/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10300:10300"
    command: [ "--model", "tiny-int8", "--language", "en" ]
    <<: [ *restart ]

#  wyoming-whispercpp:
#    build:
#      context: ./whisper-cpp/
#      dockerfile: NONGPU.Dockerfile
#    ports:
#      - "10300:10300"
#    command: [ "--model", "tiny-int8", "--language", "en" ]
#    <<: [ *restart ]

  wyoming-openwakeword:
    build:
      context: ./openwakeword/
      dockerfile: NONGPU.Dockerfile
    ports:
      - "10400:10400"
    command: [ "--preload-model", "ok_nabu" ]
    <<: [ *restart ]

#  wyoming-porcupine:
#    build:
#      context: ./porcupine1/
#      dockerfile: NONGPU.Dockerfile
#    ports:
#      - "10400:10400"
#    <<: [ *restart ]

#  wyoming-snowboy:
#    build:
#      context: ./snowboy/
#      dockerfile: NONGPU.Dockerfile
#    ports:
#      - "10400:10400"
#    <<: [ *restart ]

#  wyoming-vosk:
#    build:
#      context: ./vosk/
#      dockerfile: NONGPU.Dockerfile
#    ports:
#      - "10400:10400"
#    <<: [ *restart ]

